### ISSUE TITLE
Adding expression to also block invalid accounts

### ISSUE THREAD

**Issue by aci-drain** [inettgmbh/fail2ban-proxmox-backup-server#1]
Thanks for that helpful piece of code! You might consider adapting the regex expression to also block login attempts to invalid accounts.

Cheers 

`__suffix_failed_login = (AUTH_ERR|invalid credentials|user account disabled or expired).?`

**Comment by marcogabriel** [comment]
just merged #5 and #6 - should now also block login attempts to invalid accounts.
