### ISSUE TITLE
What will I see when my IP is banned?

### ISSUE THREAD

**Issue by scout1256** [inettgmbh/fail2ban-proxmox-backup-server#3]
What will I see when my IP is banned?
I tried 3 times wrong password and check the status and it shows my Banned IP
then I keep trying the wrong password and the action on PBS GUI ( :8007 ) is still the same 
then I type in correct password and logined!!
and check the status and it shows my Banned IP (same as above)
How do I know that it's working?

'''
Status for the jail: proxmox-backup-server
|- Filter
|  |- Currently failed: 2
|  |- Total failed:     9
|  `- File list:        /var/log/proxmox-backup/api/auth.log
`- Actions
   |- Currently banned: 2
   |- Total banned:     2
   `- Banned IP list:  XXX.XXX.XXX.XXX 192.168.2.21
'''

**Comment by marcogabriel** [comment]
If an IP is banned, an iptables rule should prevent any connection from that IP. You wouldn't even get a web interface from that IP.
