### ISSUE TITLE
Not blockin on my PBS

### ISSUE THREAD

**Issue by cglmicro** [inettgmbh/fail2ban-proxmox-backup-server#4]
Hi. 

Thanks for the code, but it's not blocking these on my PBS 2.1-5:
Feb 17 21:01:49 pbs102 proxmox-backup-proxy[1007]: authentication failure; rhost=[::ffff:192.99.233.144]:58070 msg=ticket with invalid signature
Feb 17 21:01:52 pbs102 proxmox-backup-proxy[1007]: GET /api2/json/admin/datastore: 401 Unauthorized: [client [::ffff:192.99.233.144]:58070] authentication failed - ticket with invalid signature

I dit replicate your .conf files in my ./jail.d/ and ./filter.d/, restarted with "systemctl restart fail2ban", and I can see your jail with "fail2ban-client status proxmox-backup-server".
I can also manually block IP, or subnet in this case, using "fail2ban-client set proxmox-backup-server banip 51.79.79.0/24".

What am I missing?

**Comment by secit-pl** [comment]
Check my PR https://github.com/inettgmbh/fail2ban-proxmox-backup-server/pull/6

**Comment by marcogabriel** [comment]
just merged #5 and #6, thanks again for contributing.
