### ISSUE TITLE
Not Working in PBS 2.4

### ISSUE THREAD

**Issue by francoolizarraga** [inettgmbh/fail2ban-proxmox-backup-server#7]
hi @marcogabriel , I ran into your post a few days ago and try to replicate it in my PBS without success, apparently change the code in version 2.4, and gives an error in the iptable and can not run the jail, marks the ip as banned but can continue to use, you would have an idea of how to solve it?

![image](https://github.com/inettgmbh/fail2ban-proxmox-backup-server/assets/116183200/6a49ec72-1535-4a1b-959e-d780769edfee)

Thank you

**Comment by PlayMTL** [comment]
Hey,

can you check if iptables is installed? I installed pbs on top of debian 11 and had to manually install iptables.

**Comment by marcogabriel** [comment]
I'll have a look into that. Please keep in mind that iptables is deprecated and pbs as well as pve use nftables (with an iptables-legacy "frontend").

As @PlayMTL said, it seems that iptables is not installed by default. The easiest solution would be to install it by using `apt install iptables`.

Maybe I should mention this in the readme.
