### ISSUE TITLE
PBS3 not working

### ISSUE THREAD

**Issue by elcign** [inettgmbh/fail2ban-proxmox-backup-server#9]
Could you please make this adjustment in the .conf file?

from this:
__suffix_failed_login = (AUTH_ERR|invalid credentials|user account disabled or expired).?
to this:
__suffix_failed_login = (AUTH_ERR|invalid credentials|user account disabled or expired|authentication error).?

I wasn't able to get it working until I did.

**Comment by marcogabriel** [comment]
> from this: __suffix_failed_login = (AUTH_ERR|invalid credentials|user account disabled or expired).? to this: __suffix_failed_login = (AUTH_ERR|invalid credentials|user account disabled or expired|authentication error).?

Thanks for the patch, I applied and commited it.
